# Node.js CI workflow

name: Node.js CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      IS_PUSH_MASTER: ${{ github.ref == 'refs/heads/master' }}    
    steps:
    #- name: PR Comment
    # if: env.IS_PUSH_MASTER == 'true' 
    # uses: github-actions-up-and-running/pr-comment@v1.0.1
    # with:
    #  repo-token: ${{ secrets.GITHUB_TOKEN }}
    #  message: Nice PR!👍
    - name: Check out code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '16.x'
    - name: Install dependencies
      run: yarn install --frozen-lockfile
    - name: Run lint
      run: yarn run lint
    - name: Run tests
      run: yarn run test-ci
    - name: Build
      run: yarn run build
  snyk:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build a Docker image
      run: docker build -t yanakiy/dwv .
    - name: Run Snyk to check Docker image for vulnerabilities
      continue-on-error: true
      uses: snyk/actions/docker@master
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        image: yanakiy/dwv
        args: --file=Dockerfile
  publish_to_dockerhub:
    needs: snyk
    if: ${{ github.ref == 'refs/heads/master' }}
    runs-on: ubuntu-latest
    steps:
    - name: Log in to Docker Hub
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASSWORD }}
      
    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
      with:
        images: yanakiy/dwv
      
    - name: Build and push Docker image
      uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
