# Node.js CI workflow

name: Node.js CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      IS_PUSH_MASTER: ${{ github.ref == 'refs/heads/master' }}    
    steps:
    - name: PR Comment
      if: env.IS_PUSH_MASTER == 'true' 
      uses: github-actions-up-and-running/pr-comment@v1.0.1
      with:
       repo-token: ${{ secrets.GITHUB_TOKEN }}
       message: Nice PR!👍
    - name: Check out code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '16.x'
    - name: Install dependencies
      run: yarn install --frozen-lockfile
    - name: Run lint
      run: yarn run lint
    - name: Run tests
      run: yarn run test-ci
    - name: Build
      run: yarn run build
  snyk:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build a Docker image
      run: docker build -t dwv-viewer .
    - name: Run Snyk to check Docker image for vulnerabilities
      continue-on-error: true
      uses: snyk/actions/docker@master
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        image: dwv-viewer
        args: --file=Dockerfile
